# Site wide configuration

title: xm3 倉庫
locale: zh_TW
description: 解題紀錄 x 隨筆 x 亂丟
logo: site-logo.png
search: true
url: https://xm35p4fu6.github.io
comments: true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: 呂振麒
  avatar: site-logo.png
  email: xm35p4fu6@csie.io
  disqus-shortname: xm35p4fu6
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-87806949-1
    verify: 3Y2I2JKgMnXBa5y4r6TZEUdGEyzRPrkWMEX0WKNGquE
    ad-client:
    ad-slot:
  bing-verify:
